name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DigitalOcean Container Registry
      run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

    - name: Build Docker image
      run: docker build -t registry.digitalocean.com/quix360-saas-api-repo-test/quix360-saas-api:v1.0 .

    - name: Push Docker image to registry
      run: docker push registry.digitalocean.com/quix360-saas-api-repo-test/quix360-saas-api:v1.0

    - name: Output Image Tag
      run: echo "Pushed Image: registry.digitalocean.com/quix360-saas-api-repo-test/quix360-saas-api:v1.0"
